# Generated by Django 3.0.14 on 2023-04-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_used_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Used_Coupon',
        ),
    ]
