# Generated by Django 3.0.14 on 2023-04-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0004_auto_20230325_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Addres',
            new_name='shipping_address',
        ),
    ]
