# Generated by Django 3.0.14 on 2023-04-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0006_auto_20230406_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_add',
            new_name='Addres',
        ),
    ]
